version: '3.3'
services:
  app-server:
    image: viniciusgasparin/solicitacaoDrone:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    restart: always
    networks:
      - backend

networks:
  backend:
